#!/usr/bin/env bash
# auto_pr.sh - open a PR for one fixed, regression-tested finding.
#
#   bash auto_pr.sh <fingerprint-prefix> [--root .]
#
# Strix's "one-click auto-fix as a PR" equivalent, with the same guardrail
# findings.py already enforces: a finding can only reach here if it's marked
# `fixed`, which itself requires a guarding test (findings.py refuses `fix`
# without `--test` unless forced). So a PR from this script always carries:
# the patch, the test that proves it, and the record of what was proven.
#
# This does NOT push or open the PR without asking - per the standing rule in
# this whole skill family, pushing and opening PRs are effectful actions that
# need explicit per-action confirmation, not a flag that silences the prompt.
# The script stops right before `git push` / `gh pr create` and prints the
# exact commands, rather than running them, unless CONFIRM=yes is set - and
# that env var is meant to be set by a human right before running this, not
# baked into an automated pipeline unattended.

set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Native Windows Python cannot resolve MSYS-style paths (/c/Users/...);
# cygpath -m gives the C:/Users/... form that works from any interpreter.
if command -v cygpath >/dev/null 2>&1; then
  HERE="$(cygpath -m "$HERE")"
fi
ROOT="."
FP=""

while [ $# -gt 0 ]; do
  case "$1" in
    --root) ROOT="$2"; shift 2 ;;
    *) FP="$1"; shift ;;
  esac
done

[ -z "$FP" ] && { echo "usage: auto_pr.sh <fingerprint-prefix> [--root .]"; exit 2; }

PY=""
for cand in python3 python py; do
  command -v "$cand" >/dev/null 2>&1 && "$cand" -c "" >/dev/null 2>&1 && { PY="$cand"; break; }
done
[ -z "$PY" ] && { echo "no working python interpreter found"; exit 1; }

F="$HERE/findings.py"

echo "=== Finding ==="
"$PY" "$F" --root "$ROOT" show "$FP" || exit 1

STATUS=$("$PY" -c "
import sys
sys.path.insert(0, '$HERE')
from findings import connect, resolve
conn = connect('$ROOT', create=False)
fp = resolve(conn, '$FP')
row = conn.execute('SELECT status, fix_test, title FROM findings WHERE fingerprint=?', (fp,)).fetchone()
print(row['status'] + '|' + (row['fix_test'] or '') + '|' + row['title'])
")

FSTATUS="${STATUS%%|*}"
REST="${STATUS#*|}"
FTEST="${REST%%|*}"
TITLE="${REST#*|}"

if [ "$FSTATUS" != "fixed" ]; then
  echo
  echo "Refusing: status is '$FSTATUS', not 'fixed'." >&2
  echo "A PR should only be opened for a finding that is fixed AND guarded" >&2
  echo "by a regression test - anything else is not verified yet." >&2
  exit 1
fi

if [ -z "$FTEST" ]; then
  echo
  echo "Refusing: no guarding test recorded for this finding." >&2
  echo "This should not be reachable (findings.py fix requires --test), but" >&2
  echo "checking again here because a PR is exactly the kind of irreversible," >&2
  echo "visible-to-others action that deserves a second guard." >&2
  exit 1
fi

BRANCH="swarm-fix/${FP:0:8}"
echo
echo "=== Preparing branch $BRANCH ==="
git rev-parse --git-dir >/dev/null 2>&1 || { echo "not a git repo"; exit 1; }

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Working tree has uncommitted changes beyond the fix - stopping." >&2
  echo "Commit or stash unrelated changes first so this PR contains only" >&2
  echo "the fix and its test." >&2
  exit 1
fi

echo
echo "This will run:"
echo "  git checkout -b $BRANCH"
echo "  git add -A"
echo "  git commit -m \"fix: ${TITLE}\""
echo "  git push -u origin $BRANCH"
echo "  gh pr create --title \"fix: ${TITLE}\" --body \"Guarded by ${FTEST}. See finding ${FP:0:8} in .scanme/findings.db.\""
echo

if [ "${CONFIRM:-}" != "yes" ]; then
  echo "Not running the push/PR steps automatically."
  echo "Review the commands above, then re-run with CONFIRM=yes if they look right:"
  echo "  CONFIRM=yes bash $0 $FP --root $ROOT"
  exit 0
fi

git checkout -b "$BRANCH"
git add -A
git commit -m "fix: ${TITLE}

Guarded by ${FTEST}. Confirmed failing before this fix, passing after.
Tracked as finding ${FP:0:8} in .scanme/findings.db."
git push -u origin "$BRANCH"
gh pr create \
  --title "fix: ${TITLE}" \
  --body "**Finding:** \`${FP:0:8}\` — ${TITLE}

**Guarded by:** \`${FTEST}\` — confirmed failing before this fix, passing after.

Generated by swarm. Full history: \`python scripts/findings.py show ${FP:0:8}\`"
